"""
Creates a verifiable second-life battery passport.

The passport stores battery identity, health estimation, degradation factors,
safety results and reuse grade. It is digitally signed so others can verify
that the document was not changed and who issued it.

A signature only proves document integrity and ownership of the signing key.
It does not prove that the information inside the passport is correct.

Health values are separated into:
- ESTIMATED: values generated by ML models with confidence information.
- CERTIFIED: values from official battery testing.

This keeps predicted values and verified measurements clearly separated.
"""

from __future__ import annotations

import hashlib
import json
import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

from .constants import TEAM_NAME

import numpy as np
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

logger = logging.getLogger(__name__)

PASSPORT_SCHEMA_VERSION = "1.0"


# ===========================================================================
# Key management
# ===========================================================================

def generate_keypair(key_dir: Path | str, overwrite: bool = False) -> Dict[str, Path]:
    """Creates an Ed25519 signing key pair for the battery passport issuer.

    The private key is stored without a password for demonstration purposes.
    In a real system, it should be stored securely using a key management service.
    """
    key_dir = Path(key_dir)
    key_dir.mkdir(parents=True, exist_ok=True)
    private_path = key_dir / "issuer_private.pem"
    public_path = key_dir / "issuer_public.pem"

    if private_path.exists() and not overwrite:
        logger.info("Keypair already present at %s (use overwrite=True to replace)",
                    key_dir)
        return {"private": private_path, "public": public_path}

    private_key = Ed25519PrivateKey.generate()
    private_path.write_bytes(private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ))
    private_path.chmod(0o600)

    public_path.write_bytes(private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ))

    logger.info("Generated Ed25519 keypair in %s", key_dir)
    return {"private": private_path, "public": public_path}


def load_private_key(path: Path | str) -> Ed25519PrivateKey:
    key = serialization.load_pem_private_key(
        Path(path).read_bytes(), password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise TypeError(f"{path} is not an Ed25519 private key")
    return key


def load_public_key(path: Path | str) -> Ed25519PublicKey:
    key = serialization.load_pem_public_key(Path(path).read_bytes())
    if not isinstance(key, Ed25519PublicKey):
        raise TypeError(f"{path} is not an Ed25519 public key")
    return key


def key_fingerprint(public_key: Ed25519PublicKey) -> str:
    """Creates a short identifier for a public key.

    Used to identify the correct key during verification and can be used for
    looking up the key in a registry.
    """
    raw = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return hashlib.sha256(raw).hexdigest()[:32]


# ===========================================================================
# Canonical serialisation
# ===========================================================================

def _canonical_numbers(value):
    """Converts float values that are whole numbers into integers before saving.

    JSON formatting can differ between programming languages, so keeping the same
    number format ensures that the generated signature remains valid across systems.
    """
    if isinstance(value, dict):
        return {k: _canonical_numbers(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_canonical_numbers(v) for v in value]
    if isinstance(value, bool):
        return value  # bool is a subclass of int; must not be touched
    if isinstance(value, float) and value.is_integer() and abs(value) < 2 ** 53:
        return int(value)
    return value


def canonical_json(payload: Dict) -> bytes:
    """Creates a consistent byte format for signing a JSON document.

    The same data must always produce the same bytes, so key order, spaces and
    number formatting are fixed to avoid verification failures.
    """
    return json.dumps(
        _canonical_numbers(payload), sort_keys=True, separators=(",", ":"),
        ensure_ascii=False, default=str,
    ).encode("utf-8")


def payload_digest(payload: Dict) -> str:
    return hashlib.sha256(canonical_json(payload)).hexdigest()


# ===========================================================================
# Passport construction
# ===========================================================================

def build_passport(
    battery_id: str,
    format_spec: Dict,
    health: Dict,
    degradation_factors: list,
    safety: Dict,
    second_life: Dict,
    anomaly_summary: Dict,
    model_provenance: Dict,
    certified_test: Optional[Dict] = None,
    issuer: str = f"{TEAM_NAME}",
    notes: Optional[str] = None,
) -> Dict:
    """Assemble the unsigned passport payload."""
    now = datetime.now(timezone.utc).isoformat()

    payload: Dict = {
        "schema_version": PASSPORT_SCHEMA_VERSION,
        "passport_id": str(uuid.uuid4()),
        "issued_at_utc": now,
        "issuer": issuer,

        "battery": {
            "battery_id": battery_id,
            "format": format_spec,
        },

        # Estimated health. Every number in this block is a model output.
        "health_estimate": {
            "method": "ESTIMATED",
            "method_description": (
                "Machine-learning estimate derived from charging telemetry, "
                "thermal history, impedance diagnostics and usage counters. "
                "This is NOT a certified capacity measurement."
            ),
            **health,
        },

        "degradation_factors": degradation_factors,
        "anomaly_assessment": anomaly_summary,
        "safety_assessment": safety,
        "second_life_assessment": second_life,
        "model_provenance": model_provenance,

        # Populated only when a real controlled discharge test has been performed.
        # Kept structurally separate from health_estimate so the two can never be
        # mistaken for one another.
        "certified_test": certified_test or {
            "method": "NOT_PERFORMED",
            "method_description": (
                "No certified capacity test has been performed on this unit. "
                "A certified result requires a full controlled discharge on "
                "calibrated equipment and can only be issued by an accredited "
                "test facility."
            ),
        },

        # "disclaimer": (
        #     "This passport records an ESTIMATE of battery condition produced by "
        #     "statistical models, together with its stated uncertainty. It is not "
        #     "a certificate of conformity, a safety certification, or a substitute "
        #     "for accredited testing. Reuse decisions with life-safety implications "
        #     "require certified testing."
        # ),
    }
    if notes:
        payload["notes"] = notes
    return payload


def _normalise_payload(payload: Dict) -> Dict:
    """Normalises the payload before signing.

    The signed data must match the data received during verification. This converts
    values into a consistent JSON format and removes issues caused by unsupported
    types like NaN or numpy values.
    """
    def convert(value):
        if isinstance(value, dict):
            return {k: convert(v) for k, v in value.items()}
        if isinstance(value, (list, tuple)):
            return [convert(v) for v in value]
        if isinstance(value, (np.integer,)):
            return int(value)
        if isinstance(value, (np.floating,)):
            return None if not np.isfinite(value) else float(value)
        if isinstance(value, np.bool_):
            return bool(value)
        if isinstance(value, float) and not np.isfinite(value):
            return None
        return value

    return json.loads(json.dumps(convert(payload), default=str))


def sign_passport(payload: Dict, private_key: Ed25519PrivateKey) -> Dict:
    """Creates a signed wrapper around the battery passport data.

    The original payload is kept unchanged so the verifier can check the exact data
    that was signed.
    """
    payload = _normalise_payload(payload)
    message = canonical_json(payload)
    signature = private_key.sign(message)
    public_key = private_key.public_key()

    return {
        "payload": payload,
        "signature": {
            "algorithm": "Ed25519",
            "value": signature.hex(),
            "payload_sha256": hashlib.sha256(message).hexdigest(),
            "public_key_fingerprint": key_fingerprint(public_key),
            "public_key_pem": public_key.public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo,
            ).decode("ascii"),
            "signed_at_utc": datetime.now(timezone.utc).isoformat(),
            "verification_note": (
                "The embedded public key is a convenience for offline inspection "
                "and is NOT a trust anchor. An embedded key proves nothing on its "
                "own, since anyone who alters this document can replace the key "
                "with it. Obtain the issuer's key independently and compare the "
                "fingerprint above before relying on this signature."
            ),
        },
    }


def verify_passport(
    document: Dict,
    public_key: Optional[Ed25519PublicKey] = None,
) -> Dict:
    """Verifies the passport signature and integrity.

    If no external public key is provided, the embedded key is used only to check
    that the document has not changed. A trusted external key is required to verify
    the actual issuer.
    """
    result: Dict = {
        "valid": False,
        "integrity": False,
        "trust_anchor": "none",
        "errors": [],
        "warnings": [],
    }

    if "payload" not in document or "signature" not in document:
        result["errors"].append("Document is not a signed passport envelope.")
        return result

    payload = document["payload"]
    sig_block = document["signature"]

    if sig_block.get("algorithm") != "Ed25519":
        result["errors"].append(
            f"Unsupported signature algorithm {sig_block.get('algorithm')!r}."
        )
        return result

    message = canonical_json(payload)

    expected = sig_block.get("payload_sha256")
    actual = hashlib.sha256(message).hexdigest()
    if expected != actual:
        result["errors"].append(
            "Payload digest mismatch: the document has been modified since signing."
        )
        return result

    if public_key is None:
        pem = sig_block.get("public_key_pem")
        if not pem:
            result["errors"].append(
                "No public key supplied and none embedded.")
            return result
        public_key = serialization.load_pem_public_key(pem.encode("ascii"))
        result["trust_anchor"] = "embedded (NOT authenticated)"
        result["warnings"].append(
            "Verified against the key embedded in the document. This confirms the "
            "document is internally consistent but does NOT prove who issued it. "
            "Supply the issuer's independently obtained public key for a "
            "meaningful authenticity check."
        )
    else:
        result["trust_anchor"] = "externally supplied key"

    try:
        public_key.verify(bytes.fromhex(sig_block["value"]), message)
    except (InvalidSignature, ValueError) as exc:
        result["errors"].append(f"Signature verification failed: {exc}")
        return result

    fingerprint = key_fingerprint(public_key)
    if fingerprint != sig_block.get("public_key_fingerprint"):
        result["errors"].append(
            "Key fingerprint does not match the value recorded in the signature "
            "block."
        )
        return result

    result.update({
        "valid": True,
        "integrity": True,
        "public_key_fingerprint": fingerprint,
        "passport_id": payload.get("passport_id"),
        "battery_id": payload.get("battery", {}).get("battery_id"),
        "issued_at_utc": payload.get("issued_at_utc"),
        "health_method": payload.get("health_estimate", {}).get("method"),
        "certified_test_status": payload.get("certified_test", {}).get("method"),
    })
    return result


def save_passport(document: Dict, path: Path | str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(document, fh, indent=2, ensure_ascii=False, default=str)
    return path


def load_passport(path: Path | str) -> Dict:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)
